import { ClerkProvider, auth, useUser } from '@clerk/nextjs'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = useUser;
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <nav >
            <Navbar user={user} />
          </nav>
          {children}</body>
      </html>
    </ClerkProvider>
  );
}
